---
- name: Configure yum
  hosts: jenkins
  tasks:
    - name: Install yum utils
      yum:
        name: yum-utils
        state: latest
        
    - name: Configure yum
      yum_repository:
        name: "docker_repo"
        description: Yum repo for docker
        baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
        gpgcheck: no      

    - name: Install Docker
      package:
         name: "docker-ce"
         state: present
    
    - name: Install Python
      package:
       name: "python3"
       state: present

    - name: Install Docker sdk for python
      pip:
       name: docker
    
    - name: Start Docker service
      service:
         name: "docker"
         state: started
    
    - name: webpage directory
      file:
        state: directory
        dest: "/root/webpage"
    
    - name: Pull httpd docker image
      docker_image:
         name: httpd
         tag: latest
         source: pull

    - name: Copy website to the host
      copy:
        src: ./index.html
        dest: /root/webpage
    
    - name: Run docker container
      docker_container:
         name: WebServer
         image: httpd:latest
         state: started
         exposed_ports:
         - "80"
         ports:
         - "80:80"
         volumes:
         - /root/webpage/:/usr/local/apache2/htdocs/
